name: flutter_master
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Functional Extensions & Methods 
  dartz: ^0.10.1
  
  # Networking
  dio: ^5.4.0
  freezed_annotation: 2.4.1
  json_annotation: 4.8.1
  retrofit: 4.0.3

  # State Management
  flutter_riverpod: 2.4.9
  riverpod_annotation: ^2.3.3

  # Local Storage
  secure_shared_preferences: ^0.0.4

  # Image/File Picking
  image_picker: ^1.0.5
  camera: ^0.10.5+7
  file_picker: ^6.1.1

  # Routing
  auto_route: 7.8.4

  # Connectivity
  connectivity_plus: ^5.0.2

  # Firebase
  firebase_remote_config: ^4.3.8
  firebase_core: ^2.24.2

  #SVG
  flutter_svg: ^2.0.9
  #Lottie
  lottie: ^3.1.2

  # Fonts
  google_fonts: 6.1.0

  # Widgets
  gap: ^3.0.1
  intl: ^0.19.0
  
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^16.3.0

  # Versioning
  in_app_update: ^4.2.2
  package_info_plus: ^5.0.1
  url_launcher: ^6.2.2
  path_provider: ^2.1.1
  device_preview: ^1.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_downloader: ^1.11.7
  permission_handler: ^11.3.1
  device_info_plus: ^9.1.2
  simple_barcode_scanner: ^0.1.1
  dropdown_search: ^5.0.6
  flutter_pdfview: ^1.3.2
  printing: ^5.12.0
  
  open_file_manager: ^0.0.4
  firebase_crashlytics: ^3.4.18
  firebase_auth: ^4.17.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  flutter_gen_runner: 5.3.2
  retrofit_generator: ^8.0.5
  riverpod_generator: ^2.3.9
  json_serializable: 6.7.1
  freezed: 2.4.5
  mockito: ^5.4.3
  custom_lint: 0.5.7
  riverpod_lint: 2.3.7
  auto_route_generator: 7.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/icons/
    - assets/icons/images/
    - assets/lottie/
    - assets/json/development/
    - assets/json/staging/
    - assets/json/production/
    

flutter_gen:
  output: lib/presentation/shared/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true
    flare_flutter: true
    lottie: true


